USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

CREATE SEQUENCE COLOR_UID_SEQ
START 1 INCREMENT 1;

CREATE TABLE COLORS(
COLOR_UID NUMBER(5),
COLOR_NAME VARCHAR(20));

INSERT INTO "DEMO_DB"."PUBLIC"."COLORS" VALUES 
(COLOR_UID_SEQ.NEXTVAL, 'RED'),
(COLOR_UID_SEQ.NEXTVAL, 'YELLOW'),
(COLOR_UID_SEQ.NEXTVAL, 'BLACK'),
(COLOR_UID_SEQ.NEXTVAL, 'BLUE'),
(COLOR_UID_SEQ.NEXTVAL, 'PINK');

SELECT * FROM "DEMO_DB"."PUBLIC"."COLORS";


//LAB 2
CREATE FILE FORMAT "DEMO_DB"."PUBLIC".COLOR_CSV
TYPE = 'CSV' 
COMPRESSION = 'AUTO' 
FIELD_DELIMITER = ',' 
RECORD_DELIMITER = '\n' 
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
TRIM_SPACE = FALSE 
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE 
ESCAPE = 'NONE' 
ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' 
TIMESTAMP_FORMAT = 'AUTO' 
NULL_IF = ('\\N');

select count(*) from "DEMO_DB"."PUBLIC"."COLORS";
select max(color_uid) from "DEMO_DB"."PUBLIC"."COLORS";


//setting up your RSA KEY Pair Hands-on



